# Generated by Django 2.2.7 on 2020-01-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Llegada',
            fields=[
                ('codigo_vuelo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('aerolinea', models.CharField(max_length=30)),
                ('destino', models.CharField(max_length=50)),
                ('llegada', models.TimeField(verbose_name='Hora de salida')),
                ('estado', models.CharField(choices=[('Aterrizó', 'Aterrizo'), ('Programado', 'Programado'), ('En Ruta', 'En Ruta')], max_length=30)),
                ('con_retraso', models.BooleanField()),
            ],
            options={
                'ordering': ('llegada',),
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('codigo_vuelo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('aerolinea', models.CharField(max_length=30)),
                ('destino', models.CharField(max_length=50)),
                ('partida', models.TimeField(verbose_name='Hora de salida')),
                ('estado', models.CharField(choices=[('Aterrizó', 'Aterrizo'), ('Programado', 'Programado'), ('En Ruta', 'En Ruta')], max_length=30)),
                ('con_retraso', models.BooleanField()),
            ],
            options={
                'ordering': ('partida',),
            },
        ),
    ]
