# Generated by Django 2.2.7 on 2020-01-05 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aerolinea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='llegada',
            name='aerolinea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Aerolinea'),
        ),
        migrations.AlterField(
            model_name='llegada',
            name='llegada',
            field=models.CharField(max_length=10, verbose_name='Hora de llegada'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='aerolinea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Aerolinea'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='partida',
            field=models.CharField(max_length=10, verbose_name='Hora de salida'),
        ),
    ]
