# Generated by Django 2.2.7 on 2020-01-05 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200105_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llegada',
            old_name='destino',
            new_name='origen',
        ),
    ]
