# Generated by Django 2.2.7 on 2020-01-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200105_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llegada',
            name='aerolinea',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='aerolinea',
        ),
        migrations.DeleteModel(
            name='Aerolinea',
        ),
        migrations.DeleteModel(
            name='Llegada',
        ),
        migrations.DeleteModel(
            name='Salida',
        ),
    ]
