# Generated by Django 2.2.7 on 2020-01-05 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_auto_20200105_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aerolinea',
            fields=[
                ('oaci', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
                ('logo', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('url_web', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('codigo_vuelo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('destino', models.CharField(max_length=50)),
                ('partida', models.CharField(max_length=10, verbose_name='Hora de salida')),
                ('estado', models.CharField(choices=[('Aterrizó', 'Aterrizo'), ('Programado', 'Programado'), ('En Ruta', 'En Ruta')], max_length=30)),
                ('con_retraso', models.BooleanField()),
                ('aerolinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Aerolinea')),
            ],
            options={
                'ordering': ('partida',),
            },
        ),
        migrations.CreateModel(
            name='Llegada',
            fields=[
                ('codigo_vuelo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('origen', models.CharField(max_length=50)),
                ('llegada', models.CharField(max_length=10, verbose_name='Hora de llegada')),
                ('estado', models.CharField(choices=[('Aterrizó', 'Aterrizo'), ('Programado', 'Programado'), ('En Ruta', 'En Ruta')], max_length=30)),
                ('con_retraso', models.BooleanField()),
                ('aerolinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Aerolinea')),
            ],
            options={
                'ordering': ('llegada',),
            },
        ),
    ]
