# Generated by Django 2.2.7 on 2020-01-05 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aerolinea_llegada_salida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aerolinea',
            options={'ordering': ('nombre',)},
        ),
    ]
